import { useEffect, useState } from 'react'
import { motion, useScroll, useSpring } from 'framer-motion'
import { ArrowUpRight, BriefcaseBusiness, Code2, Cpu, Github, Globe2, Instagram, Linkedin, Mail, Menu, Moon, Send, Sparkles, Sun, X, Zap } from 'lucide-react'
import './App.css'

const skills = ['Flutter', 'Dart', 'Python', 'HTML', 'CSS', 'JavaScript', 'Firebase', 'Android Development', 'AI / ML', 'IoT', 'ESP32', 'ESP8266', 'GitHub', 'Excel', 'Tally']
const projects = [
  ['01', 'AI & Face Processing', 'Practical computer vision experiments that turn cameras into useful tools.', ['Python', 'OpenCV', 'AI'], Cpu],
  ['02', 'Flutter Applications', 'Fast mobile experiences with native-feeling interactions and clean information design.', ['Flutter', 'Dart', 'Firebase'], Globe2],
  ['03', 'IoT & ESP32 Systems', 'Connected hardware prototypes that bring sensors, data and automation into the real world.', ['ESP32', 'ESP8266', 'IoT'], Zap],
  ['04', 'Smart Home Automation', 'Simple interfaces and reliable logic for responsive everyday spaces.', ['Python', 'IoT', 'Automation'], Sparkles],
  ['05', 'AI-powered Tools', 'Small intelligent utilities designed to remove friction from repetitive work.', ['AI / ML', 'Python', 'APIs'], Code2],
  ['06', 'Telegram Automation', 'Bots and workflows that connect people, notifications and useful actions.', ['Python', 'Telegram', 'APIs'], Send],
]
function Reveal({ children, delay = 0, className = '' }) { return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .16 }} transition={{ duration: .7, delay, ease: [.22, 1, .36, 1] }}>{children}</motion.div> }
function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [light, setLight] = useState(false)
  const [sent, setSent] = useState(false)
  const { scrollYProgress } = useScroll()
  const progress = useSpring(scrollYProgress, { stiffness: 100, damping: 30 })
  useEffect(() => { document.body.classList.toggle('light-theme', light) }, [light])
  const closeMenu = () => setMenuOpen(false)
  return <div className="site-shell">
    <motion.div className="scroll-progress" style={{ scaleX: progress }} /><div className="noise" />
    <header className="nav-wrap"><nav className="nav container"><a href="#top" className="brand" onClick={closeMenu}><span className="brand-mark"><Sparkles size={14} /></span>GS<span className="brand-dot">.</span></a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#about" onClick={closeMenu}>About</a><a href="#skills" onClick={closeMenu}>Skills</a><a href="#work" onClick={closeMenu}>Work</a><a href="#contact" onClick={closeMenu}>Contact</a></div><div className="nav-actions"><button className="icon-button" onClick={() => setLight(!light)} aria-label="Toggle theme">{light ? <Moon size={17} /> : <Sun size={17} />}</button><a className="nav-cta" href="/login">Face Login <ArrowUpRight size={15} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div></nav></header>
    <main id="top">
      <section className="hero container"><div className="hero-copy"><motion.div className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .4 }}>Odisha, India <span className="status-dot" /> Available for meaningful work</motion.div><motion.h1 initial={{ opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .2 }}>Building useful<br /><em>digital futures.</em></motion.h1><motion.p className="hero-lead" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .65 }}>Hi, I'm <strong>Gobinda Sahani</strong> — a computer and technology enthusiast who loves building useful experiences with AI, automation, IoT and modern application development.</motion.p><motion.div className="hero-actions" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .85 }}><a className="button button-primary" href="#work">View My Work <ArrowUpRight size={17} /></a><a className="button button-ghost" href="#contact">Contact Me <Mail size={16} /></a></motion.div><div className="hero-proof"><span><span className="proof-number">15+</span> technologies</span><span><span className="proof-number">06</span> focus areas</span><span><span className="proof-number">∞</span> curiosity</span></div></div><motion.div className="hero-portrait" initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1, delay: .2 }}><div className="portrait-aura" /><div className="portrait-frame"><img src="/profile.jpg" alt="Gobinda Sahani" /></div><div className="portrait-label"><span className="label-line" /> GOBINDA SAHANI <small>TECH ENTHUSIAST</small></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></motion.div></section>
      <section className="marquee-band"><div className="marquee-track">AI / AUTOMATION <span>✦</span> FLUTTER / MOBILE <span>✦</span> IOT / ESP32 <span>✦</span> CREATIVE CODE <span>✦</span> AI / AUTOMATION <span>✦</span> FLUTTER / MOBILE <span>✦</span></div></section>
      <section className="section container split-section" id="about"><Reveal className="section-heading"><span className="section-index">01 / ABOUT</span><h2>Curious by nature.<br /><em>Practical by design.</em></h2></Reveal><Reveal delay={.12} className="about-content"><p className="large-copy">I enjoy the space where technology becomes tangible. From a face recognition tool to an ESP32 prototype, I look for the shortest path between an interesting idea and something people can actually use.</p><div className="about-details"><div><span>Education</span><strong>B.Com — Financial Accounting</strong><small>Bapujee College, Chhendipada · 2024</small></div><div><span>Experience</span><strong>Data Entry Operator</strong><small>Shreeram Transport · Jan–Oct 2024</small></div></div></Reveal></section>
      <section className="section container" id="skills"><Reveal className="section-heading centered"><span className="section-index">02 / TOOLKIT</span><h2>Technologies I<br /><em>work with.</em></h2></Reveal><div className="skills-grid">{skills.map((skill, index) => <Reveal key={skill} delay={index * .035}><div className="skill-chip"><span>{String(index + 1).padStart(2, '0')}</span>{skill}<ArrowUpRight size={14} /></div></Reveal>)}</div></section>
      <section className="section container" id="work"><Reveal className="section-heading project-heading"><span className="section-index">03 / SELECTED WORK</span><h2>Small projects.<br /><em>Real momentum.</em></h2><p>Experiments, tools and systems shaped by a love for learning through making.</p></Reveal><div className="project-grid">{projects.map(([number, title, text, tags, Icon], index) => <Reveal key={title} delay={index * .06}><article className="project-card"><div className="project-top"><span>{number}</span><Icon size={23} /></div><div><h3>{title}</h3><p>{text}</p></div><div className="project-bottom"><div className="tag-list">{tags.map(tag => <span key={tag}>{tag}</span>)}</div><a href="https://github.com/Gobinda988888" target="_blank" rel="noreferrer" aria-label={`View ${title} on GitHub`}><Github size={18} /></a></div></article></Reveal>)}</div></section>
      <section className="section container experience-grid"><Reveal className="section-heading"><span className="section-index">04 / EXPERIENCE</span><h2>Where I learned<br /><em>to make it work.</em></h2></Reveal><Reveal className="timeline"><div className="timeline-item"><span className="timeline-date">JAN 2024 — OCT 2024</span><div><h3>Data Entry Operator</h3><p>Shreeram Transport</p><ul><li>Managed Excel vehicle records and computerized data.</li><li>Organized operational information with accuracy and consistency.</li><li>Supported day-to-day data workflows for the transport team.</li></ul></div></div><div className="timeline-item"><span className="timeline-date">2024</span><div><h3>Bachelor of Commerce</h3><p>Financial Accounting · Bapujee College, Chhendipada</p><ul><li>Completed a foundation in accounting, business and structured thinking.</li></ul></div></div></Reveal></section>
      <section className="section services-band"><div className="container"><Reveal className="section-heading centered"><span className="section-index">05 / WHAT I DO</span><h2>Useful technology,<br /><em>carefully applied.</em></h2></Reveal><div className="service-list">{['Web & App Development', 'AI & Automation', 'IoT Projects', 'Flutter Development', 'Python Development', 'Technical Solutions'].map((service, index) => <Reveal key={service} delay={index * .05}><div className="service-row"><span>0{index + 1}</span><h3>{service}</h3><ArrowUpRight size={20} /></div></Reveal>)}</div></div></section>
      <section className="contact-section container" id="contact"><Reveal className="contact-intro"><span className="section-index">06 / SAY HELLO</span><h2>Have an idea?<br /><em>Let's make it useful.</em></h2><p>Open to conversations about technology, creative projects and practical digital solutions.</p><div className="contact-links"><a href="mailto:gobinda@example.com"><Mail size={17} /> gobinda@example.com</a><span><Globe2 size={17} /> Odisha, India</span></div></Reveal><Reveal delay={.1} className="contact-form-wrap"><form onSubmit={(event) => { event.preventDefault(); setSent(true) }}><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@example.com" /></label><label>Message<textarea required rows="4" placeholder="Tell me about the idea..." /></label><button className="button button-primary" type="submit">{sent ? 'Message ready ✓' : 'Send Message'} <Send size={16} /></button></form></Reveal></section>
    </main>
    <footer className="footer container"><div><strong>Gobinda Sahani<span>.</span></strong><p>Designed & built with curiosity.</p></div><div className="socials"><a href="https://github.com/Gobinda988888" target="_blank" rel="noreferrer" aria-label="GitHub"><Github /></a><a href="https://linkedin.com" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram /></a><a href="mailto:gobinda@example.com" aria-label="Email"><Mail /></a></div><span className="copyright">© 2026 Gobinda Sahani</span></footer><a className="resume-fab" href="mailto:gobinda@example.com?subject=Portfolio%20conversation"><BriefcaseBusiness size={17} /> Let's talk</a>
  </div>
}
export default App
